### ISSUE TITLE
Yarn install issue on Windows 10

### ISSUE THREAD

**Issue by ionrazvan** [davidtucker/ps-serverless-app#8]
Hi,
I got the code from the p1 branch.
When running yarn in the root folder I get the following error:
error An unexpected error occurred: "EISDIR: illegal operation on a directory, symlink 'E:\\WORK\\AWS\\ps-serverless-app\\infrastructure' -> 'E:\\WORK\\AWS\\ps-serverless-app\\node_modules\\@ps-serverless\\infrastructure'".

In the root folder there is a node_modules\@ps-serverless folder but it is empty; other node modules are there.
I guess something is wrong when it tries to link to the infrastructure folder, but I cannot figure out what. 

I am running the yarn command from the command prompt launched as admin in windows 10 64bit.
Yarn 1.22.17, npm 8.1.0, nodejs v17.0.0.

Thank you,
Razvan

**Comment by rluisnpt1** [comment]
Well make sure, you have the right configuration in your yarn workspace

https://classic.yarnpkg.com/lang/en/docs/workspaces/
https://yarnpkg.com/cli/workspace
Pay attention to the names in the workspace at your package.json in the root of the project, and In the subfolder/project/package.json should end with same name. 
As Best practice, the community uses the '@root-project-name/project' in order to have a better visibility. however you can add any name. just make sure that you  have that name in the package.json root.
in the root of your projects use the command:
Yarn
yarn workspaces webapp start 
yarn workspaces webapp add -D libname@version

**Comment by davidtucker** [comment]
I just tested this with the same specs, and I did not see this issue.  Feel free to reopen if you see this again.
